<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h1>
        Studienarbeit suchen
    </h1>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ?>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <?php if(isset($this->article)): ?>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Titel:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getTitel(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Gruppenmitglieder:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getGruppenmitglieder(); ?>
            </div>
        </div>
    <?php endif; ?>
</div>



