<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h1>
        Module:
    </h1>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <?php foreach ($this->entries as $entry): ?>
        <h2>
            <?php echo $entry->getBezeichnung(); ?>
        </h2>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Semester:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $entry->getSemester(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Dozent:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $entry->getDozent()?>
            </div>
        </div>
        <hr/>
    <?php endforeach ?>
</div>
