<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h1>
        Modul suchen
    </h1>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ?>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <?php if(isset($this->article)): ?>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Bezeichnung:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getBezeichnung(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Kurzbeschreibung:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getKurzbeschreibung(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Semester:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getSemester(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                Dozent:
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->article->getDozent(); ?>
            </div>
        </div>
    <?php endif; ?>
</div>



