<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ESA3</title>
  <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
</head>
<body>
    <div id="header" style="background-color: #EEEEEE; height: 30px;">
        <div id="header-logo" style="float: left">
            <a href="/">
                <b>Index</b>
            </a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <?php echo $this->layout()->content ?>
        </div>
    </div>
</body>
</html>