<p>
    <a href="<?php echo $this->url(
        array(
            'controller' => 'blog',
            'action'     => 'sign'
        ),
        'default',
        true) ?>">Blogeintrag machen</a>
</p>

Blogeinträge: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
        <dt><?php echo $this->escape($entry->title) ?></dt>
        <dd><?php echo $this->escape($entry->text) ?></dd>
    <?php endforeach ?>
</dl>
